function rewards = oldRewardFunction(belief)

r = 5;

%Positive reward for playing in the same key, negative reward for playing
%out of it.
rv = [r; -r; r; -r; r; r; -r; r; -r; r; -r; r]; 
rv2 = [r; -r; r; r; -r; r; -r; r; r; -r; r; -r];
RewardMatrix = [rv, circshift(rv, 1), circshift(rv, 2), circshift(rv, 3),...
    circshift(rv, 4), circshift(rv, 5), circshift(rv, 6), ...
    circshift(rv, 7), circshift(rv, 8), circshift(rv, 9), ...
    circshift(rv, 10), circshift(rv, 11),...
    rv2, circshift(rv2, 1), circshift(rv2, 2), circshift(rv2, 3),...
    circshift(rv2, 4), circshift(rv2, 5), circshift(rv2, 6), ...
    circshift(rv2, 7), circshift(rv2, 8), circshift(rv2, 9), ...
    circshift(rv2, 10), circshift(rv2, 11)]';

rewards = belief*RewardMatrix;

end